namespace ProyectoUnion.Application.Dtos.Socios;

/// <summary>
/// Ninguno de los campos marcados "ficha médica completa" (<see cref="GrupoSanguineo"/>,
/// <see cref="ObservacionesMedicas"/>, <see cref="CoberturaMedicaId"/>,
/// <see cref="CoberturaMedicaNombre"/>, <see cref="PlanId"/>, <see cref="PlanNombre"/>,
/// <see cref="FichaMedicaFechaEmision"/>, <see cref="FichaMedicaFechaVencimiento"/>) se
/// completa para roles distintos de SuperAdministrador/Administrador (regla transversal,
/// SPEC.md §2.2) — quedan en <c>null</c> y solo se expone <see cref="FichaMedicaVigencia"/>.
/// </summary>
public sealed record SocioResponse(
    Guid Id,
    string NumeroSocio,
    string Apellido,
    string Nombres,
    string DNI,
    string? CUIL,
    DateTime FechaNacimiento,
    string? Genero,
    string? Nacionalidad,
    string TipoPago,
    Guid CategoriaId,
    string CategoriaNombre,
    string? Telefono,
    string? Celular,
    string Email,
    string? Domicilio,
    string? Localidad,
    string? Provincia,
    string? CodigoPostal,
    Guid? CoberturaMedicaId,
    string? CoberturaMedicaNombre,
    Guid? PlanId,
    string? PlanNombre,
    string? GrupoSanguineo,
    string? ContactoEmergencia,
    string? ObservacionesMedicas,
    DateTime? FichaMedicaFechaEmision,
    DateTime? FichaMedicaFechaVencimiento,
    string? FotoUrl,
    Guid? GrupoFamiliarId,
    string? Parentesco,
    string Modalidad,
    string Estado,
    DateTime FechaAlta,
    DateTime? FechaBaja,
    string? MotivoBaja,
    string CodigoQr,
    DateTime? ConsentimientoDatosSaludFecha,
    string? FichaMedicaVigencia);
